# Generated by Django 5.2.6 on 2025-12-01 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMC', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvaliacaoIMC',
            fields=[
                ('cpf', models.CharField(max_length=11, primary_key=True, serialize=False, unique=True, verbose_name='CPF')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1, verbose_name='Sexo')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('escola', models.CharField(max_length=255, verbose_name='Escola')),
                ('peso', models.FloatField(verbose_name='Peso (kg)')),
                ('altura', models.FloatField(verbose_name='Altura (m)')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='avaliacoes_fotos/', verbose_name='Foto da Pessoa Avaliada')),
                ('classificacao_imc', models.CharField(blank=True, editable=False, max_length=50, null=True, verbose_name='Classificação do IMC')),
            ],
            options={
                'verbose_name': 'Avaliação de IMC',
                'verbose_name_plural': 'Avaliações de IMC',
            },
        ),
        migrations.DeleteModel(
            name='Avaliar_IMC',
        ),
    ]
